version: "3.8"
services:
  database:
    image: postgres
    container_name: postgres-db
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital-design-final-task
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "4123:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    restart: always
    networks:
      - java-digital-design

  digital-design-task:
    image: digital-design-task:1
    networks:
      - java-digital-design

networks:
  java-digital-design:
